[colors]
background = "#191724"
secondaryBackground = "#1f1d2e"
foreground = "#e0def4"
secondaryForeground = "#e0def4"

[editor]
margin = "24"

    [editor.font]
    family = "Noto Serif"
    size = "16"

[header]
margin = "4"

    [header.font]
    family = "Ubuntu Mono"
    size = "12"